title: Md Mustahsin Farhan Chowdhury
logo: /assets/img/profile_pic.png
description: After graduating with an engineering degree, I embarked on a journey to explore within my field. I delved into programming, cybersecurity, networking, and ultimately discovered a passion for data analytics. This passion led to my decision to pursue a graduate degree in data science. I am open to opportunities to learn and research alongside seasoned professionals.
show_downloads: false
theme: jekyll-theme-minimal
