title: Mustahsin Farhan
name: "Mustahsin Farhan | Portfolio"
logo: /assets/img/profile_pic.png
description: Full-time Embedded Software Developer eager to contribute to cutting-edge research and product development. Proficient in C/C++, Python, and data analytics. Experienced in robotics, data and IoT projects. 
show_downloads: false
theme: jekyll-theme-minimal
